# Generated by Django 5.1.7 on 2025-03-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIGeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, verbose_name='کلمات کلیدی')),
                ('generated_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان تولید شده')),
                ('generated_content', models.TextField(blank=True, verbose_name='محتوای تولید شده')),
                ('generated_meta_description', models.TextField(blank=True, verbose_name='توضیحات متا تولید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'محتوای تولید شده با هوش مصنوعی',
                'verbose_name_plural': 'محتواهای تولید شده با هوش مصنوعی',
                'ordering': ['-created_at'],
            },
        ),
    ]
